Set the actual logging levels
* The highest logging level is "trace", not "all"

The value "all" for LOGGING_LEVEL_ROOT is logged as invalid at startup:
java.lang.IllegalArgumentException: No enum constant org.springframework.boot.logging.LogLevel.all

* Add trace logging level

* Revert "Add trace logging level"

This reverts commit a0eb52f3040d7dac814d962ea59d4b6a95e1b1ba.

Co-authored-by: Roman Zabaluev <rzabaluev@provectus.com>